// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYRw7349JMroRB5kH8Ju6pAcRxgnFC1l8',
    appId: '1:463716535452:web:b10eb295d9893a457ab159',
    messagingSenderId: '463716535452',
    projectId: 'mediconnect-65d5646421-medi',
    authDomain: 'mediconnect-65d5646421-medi.firebaseapp.com',
    storageBucket: 'mediconnect-65d5646421-medi.firebasestorage.app',
    measurementId: 'G-MJ4QR18GBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNJhJkif7iBq6DrQKC0mtq3cRQ4uhwXnA',
    appId: '1:463716535452:android:affeaf3aadbd64117ab159',
    messagingSenderId: '463716535452',
    projectId: 'mediconnect-65d5646421-medi',
    storageBucket: 'mediconnect-65d5646421-medi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVcGjYXM4dgjJEn_O3Elb2rFXKgpJVK3c',
    appId: '1:463716535452:ios:3d428f673019e9d97ab159',
    messagingSenderId: '463716535452',
    projectId: 'mediconnect-65d5646421-medi',
    storageBucket: 'mediconnect-65d5646421-medi.firebasestorage.app',
    iosBundleId: 'com.example.mediconnectClear',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVcGjYXM4dgjJEn_O3Elb2rFXKgpJVK3c',
    appId: '1:463716535452:ios:3d428f673019e9d97ab159',
    messagingSenderId: '463716535452',
    projectId: 'mediconnect-65d5646421-medi',
    storageBucket: 'mediconnect-65d5646421-medi.firebasestorage.app',
    iosBundleId: 'com.example.mediconnectClear',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYRw7349JMroRB5kH8Ju6pAcRxgnFC1l8',
    appId: '1:463716535452:web:5d263760549288947ab159',
    messagingSenderId: '463716535452',
    projectId: 'mediconnect-65d5646421-medi',
    authDomain: 'mediconnect-65d5646421-medi.firebaseapp.com',
    storageBucket: 'mediconnect-65d5646421-medi.firebasestorage.app',
    measurementId: 'G-YVTPB8P45W',
  );
}
